# Travis-CI Build for keyczar-dotnet 
# see travis-ci.org for details

language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

solution: ImpromptuInterface.sln

mono: latest
dotnet: 2.0.0

install:
  - msbuild /t:restore

script:
 - msbuild
 - .ci/RunTests.sh

branches:
  only:
    - master